version: "3"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.6
    ports:
      - 22181:2181
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
      - ZOOKEEPER_SYNC_LIMIT=2

  kafka:
    image: confluentinc/cp-kafka:5.5.6
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=LISTENER_INTERNAL://kafka:9092,LISTENER_EXTERNAL://localhost:29092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=LISTENER_INTERNAL:PLAINTEXT,LISTENER_EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=LISTENER_INTERNAL
      - KAFKA_BROKER_ID=1
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1

  kowl:
    image: quay.io/cloudhut/kowl:master
    depends_on: 
      - kafka 
    ports: 
      - 8081:8080
    environment:
      - KAFKA_BROKERS=kafka:9092